import { Injectable } from '@angular/core';
import { BookComment } from '../../models/comment.model';

@Injectable({
  providedIn: 'root',
})
export class CommentsService {
  allComments: BookComment[] = [
    {
      commentId: 1,
      bookId: 1,
      userId: 1,
      userName: 'Marie Dupont',
      rating: 4,
      content: 'Très bien écrit, les personnages sont attachants.',
      userAvatar: 'avatar-01.jpg',
    },
    {
      commentId: 2,
      bookId: 1,
      userId: 5,
      userName: 'Chloé Bernard',
      rating: 4,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-05.jpg',
    },
    {
      commentId: 3,
      bookId: 1,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 1,
      content: 'Trop de longueurs, je me suis ennuyé.',
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 4,
      bookId: 2,
      userId: 9,
      userName: 'Camille Rousseau',
      rating: 5,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-09.jpg',
    },
    {
      commentId: 5,
      bookId: 2,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 3,
      content: 'Une lecture moyenne, ni bonne ni mauvaise.',
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 6,
      bookId: 3,
      userId: 4,
      userName: 'Lucas Moreau',
      rating: 2,
      content: 'Trop de longueurs, je me suis ennuyé.',
      userAvatar: 'avatar-04.jpg',
    },
    {
      commentId: 7,
      bookId: 3,
      userId: 9,
      userName: 'Camille Rousseau',
      rating: 2,
      content: 'Les personnages manquent de profondeur.',
      userAvatar: 'avatar-09.jpg',
    },
    {
      commentId: 8,
      bookId: 3,
      userId: 2,
      userName: 'Jean Martin',
      rating: 2,
      content: "Je n'ai pas réussi à finir le livre.",
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 9,
      bookId: 4,
      userId: 10,
      userName: 'Léo Girard',
      rating: 3,
      content: "L'histoire est bien construite, mais un peu lente à mon goût.",
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 10,
      bookId: 4,
      userId: 4,
      userName: 'Lucas Moreau',
      rating: 3,
      content: 'Une lecture agréable sans être exceptionnelle.',
      userAvatar: 'avatar-04.jpg',
    },
    {
      commentId: 11,
      bookId: 4,
      userId: 8,
      userName: 'Nathan Petit',
      rating: 5,
      content: 'Très bien écrit, les personnages sont attachants.',
      userAvatar: 'avatar-08.jpg',
    },
    {
      commentId: 12,
      bookId: 5,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 1,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 13,
      bookId: 5,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 3,
      content: 'Une lecture moyenne, ni bonne ni mauvaise.',
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 14,
      bookId: 5,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 1,
      content: "Déçu par ce livre, je m'attendais à mieux.",
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 15,
      bookId: 5,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 4,
      content: 'Très bien écrit, les personnages sont attachants.',
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 16,
      bookId: 6,
      userId: 7,
      userName: 'Emma Lefevre',
      rating: 4,
      content: 'Très bien écrit, les personnages sont attachants.',
      userAvatar: 'avatar-07.jpg',
    },
    {
      commentId: 17,
      bookId: 6,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 1,
      content: 'Trop de longueurs, je me suis ennuyé.',
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 18,
      bookId: 6,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 5,
      content: "Un livre captivant, je l'ai dévoré en une journée !",
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 19,
      bookId: 7,
      userId: 10,
      userName: 'Léo Girard',
      rating: 1,
      content: "Déçu par ce livre, je m'attendais à mieux.",
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 20,
      bookId: 7,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 4,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 21,
      bookId: 7,
      userId: 2,
      userName: 'Jean Martin',
      rating: 2,
      content: 'Les personnages manquent de profondeur.',
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 22,
      bookId: 7,
      userId: 1,
      userName: 'Marie Dupont',
      rating: 3,
      content: 'Une lecture agréable sans être exceptionnelle.',
      userAvatar: 'avatar-01.jpg',
    },
    {
      commentId: 23,
      bookId: 8,
      userId: 5,
      userName: 'Chloé Bernard',
      rating: 2,
      content: 'Trop de longueurs, je me suis ennuyé.',
      userAvatar: 'avatar-05.jpg',
    },
    {
      commentId: 24,
      bookId: 8,
      userId: 5,
      userName: 'Chloé Bernard',
      rating: 3,
      content: 'Une lecture moyenne, ni bonne ni mauvaise.',
      userAvatar: 'avatar-05.jpg',
    },
    {
      commentId: 25,
      bookId: 9,
      userId: 2,
      userName: 'Jean Martin',
      rating: 1,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 26,
      bookId: 9,
      userId: 8,
      userName: 'Nathan Petit',
      rating: 2,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-08.jpg',
    },
    {
      commentId: 27,
      bookId: 9,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 4,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 28,
      bookId: 10,
      userId: 10,
      userName: 'Léo Girard',
      rating: 4,
      content: 'Une histoire émouvante et pleine de rebondissements.',
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 29,
      bookId: 10,
      userId: 2,
      userName: 'Jean Martin',
      rating: 3,
      content: 'Une lecture agréable sans être exceptionnelle.',
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 30,
      bookId: 10,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 5,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 31,
      bookId: 11,
      userId: 10,
      userName: 'Léo Girard',
      rating: 4,
      content: "J'ai adoré, c'était un véritable coup de cœur.",
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 32,
      bookId: 11,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 4,
      content: "Un livre captivant, je l'ai dévoré en une journée !",
      userAvatar: 'avatar-06.jpg',
    },
    {
      commentId: 33,
      bookId: 11,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 3,
      content: "C'était intéressant, mais pas inoubliable.",
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 34,
      bookId: 12,
      userId: 2,
      userName: 'Jean Martin',
      rating: 2,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 35,
      bookId: 12,
      userId: 2,
      userName: 'Jean Martin',
      rating: 5,
      content: "Un livre captivant, je l'ai dévoré en une journée !",
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 36,
      bookId: 12,
      userId: 5,
      userName: 'Chloé Bernard',
      rating: 4,
      content: 'Une histoire émouvante et pleine de rebondissements.',
      userAvatar: 'avatar-05.jpg',
    },
    {
      commentId: 37,
      bookId: 12,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 4,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 38,
      bookId: 13,
      userId: 8,
      userName: 'Nathan Petit',
      rating: 5,
      content: 'Très bien écrit, les personnages sont attachants.',
      userAvatar: 'avatar-08.jpg',
    },
    {
      commentId: 39,
      bookId: 13,
      userId: 4,
      userName: 'Lucas Moreau',
      rating: 2,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-04.jpg',
    },
    {
      commentId: 40,
      bookId: 13,
      userId: 7,
      userName: 'Emma Lefevre',
      rating: 1,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-07.jpg',
    },
    {
      commentId: 41,
      bookId: 14,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 1,
      content: "Je n'ai pas réussi à finir le livre.",
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 42,
      bookId: 14,
      userId: 8,
      userName: 'Nathan Petit',
      rating: 4,
      content: "J'ai adoré, c'était un véritable coup de cœur.",
      userAvatar: 'avatar-08.jpg',
    },
    {
      commentId: 43,
      bookId: 14,
      userId: 1,
      userName: 'Marie Dupont',
      rating: 2,
      content: 'Trop de longueurs, je me suis ennuyé.',
      userAvatar: 'avatar-01.jpg',
    },
    {
      commentId: 44,
      bookId: 15,
      userId: 2,
      userName: 'Jean Martin',
      rating: 1,
      content: "Je n'ai pas réussi à finir le livre.",
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 45,
      bookId: 15,
      userId: 2,
      userName: 'Jean Martin',
      rating: 1,
      content: 'Trop de longueurs, je me suis ennuyé.',
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 46,
      bookId: 15,
      userId: 1,
      userName: 'Marie Dupont',
      rating: 1,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-01.jpg',
    },
    {
      commentId: 47,
      bookId: 16,
      userId: 7,
      userName: 'Emma Lefevre',
      rating: 2,
      content: 'Les personnages manquent de profondeur.',
      userAvatar: 'avatar-07.jpg',
    },
    {
      commentId: 48,
      bookId: 16,
      userId: 1,
      userName: 'Marie Dupont',
      rating: 5,
      content: 'Une histoire émouvante et pleine de rebondissements.',
      userAvatar: 'avatar-01.jpg',
    },
    {
      commentId: 49,
      bookId: 16,
      userId: 10,
      userName: 'Léo Girard',
      rating: 3,
      content: 'Une lecture moyenne, ni bonne ni mauvaise.',
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 50,
      bookId: 16,
      userId: 7,
      userName: 'Emma Lefevre',
      rating: 1,
      content: 'Les personnages manquent de profondeur.',
      userAvatar: 'avatar-07.jpg',
    },
    {
      commentId: 51,
      bookId: 17,
      userId: 10,
      userName: 'Léo Girard',
      rating: 2,
      content: "Je n'ai pas accroché, l'histoire est trop prévisible.",
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 52,
      bookId: 17,
      userId: 10,
      userName: 'Léo Girard',
      rating: 1,
      content: "Déçu par ce livre, je m'attendais à mieux.",
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 53,
      bookId: 17,
      userId: 6,
      userName: 'Thomas Garcia',
      rating: 3,
      content: "Le livre est correct, mais il m'a manqué quelque chose.",
      userAvatar: 'avatar-16.jpg',
    },
    {
      commentId: 54,
      bookId: 17,
      userId: 2,
      userName: 'Jean Martin',
      rating: 5,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 55,
      bookId: 18,
      userId: 1,
      userName: 'Marie Dupont',
      rating: 5,
      content: 'Une histoire émouvante et pleine de rebondissements.',
      userAvatar: 'avatar-01.jpg',
    },
    {
      commentId: 56,
      bookId: 18,
      userId: 9,
      userName: 'Camille Rousseau',
      rating: 5,
      content: 'Magnifique, je recommande fortement !',
      userAvatar: 'avatar-09.jpg',
    },
    {
      commentId: 57,
      bookId: 18,
      userId: 4,
      userName: 'Lucas Moreau',
      rating: 5,
      content: "Un livre captivant, je l'ai dévoré en une journée !",
      userAvatar: 'avatar-04.jpg',
    },
    {
      commentId: 58,
      bookId: 19,
      userId: 10,
      userName: 'Léo Girard',
      rating: 1,
      content: "Déçu par ce livre, je m'attendais à mieux.",
      userAvatar: 'avatar-10.jpg',
    },
    {
      commentId: 59,
      bookId: 19,
      userId: 8,
      userName: 'Nathan Petit',
      rating: 3,
      content: 'Une lecture agréable sans être exceptionnelle.',
      userAvatar: 'avatar-08.jpg',
    },
    {
      commentId: 60,
      bookId: 20,
      userId: 2,
      userName: 'Jean Martin',
      rating: 1,
      content: 'Les personnages manquent de profondeur.',
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 61,
      bookId: 20,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 5,
      content: "Un livre captivant, je l'ai dévoré en une journée !",
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 62,
      bookId: 20,
      userId: 7,
      userName: 'Emma Lefevre',
      rating: 3,
      content: "Le livre est correct, mais il m'a manqué quelque chose.",
      userAvatar: 'avatar-07.jpg',
    },
    {
      commentId: 63,
      bookId: 21,
      userId: 2,
      userName: 'Jean Martin',
      rating: 3,
      content: 'Une lecture moyenne, ni bonne ni mauvaise.',
      userAvatar: 'avatar-02.jpg',
    },
    {
      commentId: 64,
      bookId: 21,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 1,
      content: "Déçu par ce livre, je m'attendais à mieux.",
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 65,
      bookId: 21,
      userId: 3,
      userName: 'Sophie Lambert',
      rating: 5,
      content: 'Très bien écrit, les personnages sont attachants.',
      userAvatar: 'avatar-03.jpg',
    },
    {
      commentId: 66,
      bookId: 22,
      userId: 4,
      userName: 'Lucas Moreau',
      rating: 4,
      content: 'Une histoire émouvante et pleine de rebondissements.',
      userAvatar: 'avatar-04.jpg',
    },
    {
      commentId: 67,
      bookId: 22,
      userId: 7,
      userName: 'Emma Lefevre',
      rating: 5,
      content: 'Une histoire émouvante et pleine de rebondissements.',
      userAvatar: 'avatar-07.jpg',
    },
  ];

  getCommentsByBookId(bookId: number): BookComment[] {
    let arrayOfComments = [];
    for (let i = 0; i < this.allComments.length; i++) {
      if (this.allComments[i].bookId === bookId) {
        arrayOfComments.push(this.allComments[i]);
      }
    }
    return arrayOfComments;
  }
}
