export enum Genre {
  Fiction = 'fiction',
  NonFiction = 'non fiction',
  Mystery = 'merveilleux',
  ScienceFiction = 'science fiction',
  Fantasy = 'fantaisie',
  Romance = 'romance',
  Thriller = 'policier',
  Historical = 'historique',
  Biography = 'biographie',
  SelfHelp = 'développement personnel',
  Horror = 'horreur',
  PoliticalScience = 'sciences politiques',
  Economics = 'économie',
}
